### ISSUE TITLE
'sync' is not present in simulation

### ISSUE THREAD

**Issue by BracketMaster** [jfng/minerva-examples#1]
Hello @jfng, what version/branch of nMigen-SOC are you using?
I am able to run commit 080df0aa266e410372e4d487bdde6d5c5e0edebc from December just fine.
I get the following error when trying to run the lastest commit.

```bash
$python3 core.py 
Traceback (most recent call last):
  File "core.py", line 134, in <module>
    sim.add_clock(1e-6)
  File ".virtualenvs/minerva/lib/python3.7/site-packages/nmigen/back/pysim.py", line 477, in add_clock
    .format(domain))
ValueError: Domain 'sync' is not present in simulation
```

**Comment by BracketMaster** [comment]
OK. Figured it out.
The Minerva codebase currently uses an old version of nMigen from Pypi.
But this repository uses new nmigen features from nmigen-soc.
You must remove the nmigen Minerva installs.
